install.packages("data.table",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("xgboost",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("Rtsne",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("dplyr",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("ggplot2",repos= "http://lib.stat.cmu.edu/R/CRAN/")